### ISSUE TITLE
최근 검색 기록 추가

### ISSUE THREAD

**Issue by vectorch9** [Instagram-Clone-Coding/Spring_instagram-clone#162]
## Feature Description
- 최근 검색 기록 추가
- 관련 DB table 작성 필요

## Todo list
- [x] 최근 검색 기록 추가 API
- [x] 최근 검색 기록 조회 API
- [x] 최근 검색 기록 삭제 API
