### ISSUE TITLE
이메일 서비스 리팩토링 및 테스트 작성

### ISSUE THREAD

**Issue by vectorch9** [Instagram-Clone-Coding/Spring_instagram-clone#233]
## Feature Description
- 

## Todo list
- [x] 리팩토링
  - [x] 이메일 서비스 리팩토링
  - [ ] 이메일 코드 서비스 리팩토링
  - [x] Async 메서드 활성화
  - [x] Response time 측정 
- [x] 테스트 작성
